/-
Copyright (c) 2026 Michele Chiari. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Michele Chiari
-/
import Stlsat.Jump.UnconditionalSoundness
import Stlsat.Jump.Completeness
import Stlsat.Jump.Termination
import Stlsat.Jump.Construction

/-!
# The STL tableau with JUMP

This umbrella module exports the JUMP tableau and its reusable semantic
infrastructure, the unconditional soundness theorem, and the completeness-guard
regression showing that independent target windows disable an unsafe JUMP.  It
also exports operational termination of branches generated by the full rule.
Every strict-normal-form formula has a finite, fully developed tableau.
-/
